#!/bin/bash
export TOR_VERSION="0.4.2.5"
export OR_PORT="9001"
export DIR_PORT="9030"
export NICKNAME="NotProvided"
export CONTACT_INFO="not-provided@example.com"
export BANDWIDTH_RATE="250 KBytes"
export BANDWIDTH_BURST="500 KBytes"
export MAX_MEM="512 MB"
export ACCOUNTING_MAX="0"
export ACCOUNTING_START="month 1 00:00"
